# Generated by Django 3.2.25 on 2024-08-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_indentificador_typeuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuarios',
            name='identificador',
            field=models.ForeignKey(db_column='indentificador_id', on_delete=django.db.models.deletion.CASCADE, to='backend.indentificador'),
        ),
    ]
