# Generated by Django 3.2.25 on 2024-11-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_datosusuarios_identificador'),
    ]

    operations = [
    ]
